### ISSUE TITLE
好像有点问题

### ISSUE THREAD

**Issue by Qu1n-22** [Luz233/fuck_hzsfxy_daka#1]
`    submitRes = req.post(url=url_submit,headers = headers_submit,data=datas)
    print(submitRes.text)
    if "提交成功" in submitRes.text:
        print("提交成功")
`
submitRes最后是同时包含 ‘提交成功’ 和 ’提交失败‘ 文本，

![QQ截图20211216102932](https://user-images.githubusercontent.com/58621926/146296935-3598485d-73b1-4203-b90d-5df33f7d03ec.png)

> {"callback":"function(res){\nvar as=arguments; return FR.tc(function(){;return eval(\"(function(fr_submitinfo){try{if (fr_submitinfo.success) {\\n /*FR.Msg.toast('提交成功');*/\\n setTimeout(function() {\\n     _g('0d231dab-0ffc-4891-b79a-08d2b894ead6').writeReport();   //执行提交入库操作 \\n    }, 2000);\\n        var url = FR.cjkEncode(\\\"/webroot/decision/view/form?reportlet=xxkj/mobile/bpa/tjjg.cpt\\\");  \\n    FR.doHyperlinkByGet({  \\n        url: url,  \\n        title: '报平安'  \\n    });     \\n} else {\\n FR.Msg.toast('提交失败');\\n}\\n}catch(ex){FR.Logger.error(ex);FR.Msg.toast(FR.i18nText('Custom')+'JS'+FR.i18nText('Error')+' : '+ex.message);}}).createDelegate(this, [{\\\"success\\\":true}], 0).apply(this, arguments)\");},

应该不能作为提交成功的判断 吧
用了以后虽然显示提交成功但是再进打卡页面，没有提示今日已经打卡

**Comment by Luz233** [comment]
只要参数不错就没问题 我挂了三个月了
